# Generated by Django 4.1.5 on 2023-02-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
