# Generated by Django 4.1.5 on 2023-02-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_menu_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(height_field=100, upload_to='default', width_field=100),
        ),
    ]
