# Generated by Django 4.1.5 on 2023-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('phone_number', models.IntegerField()),
                ('dishes_name', models.CharField(max_length=100)),
                ('how_many', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
