# Generated by Django 4.1.5 on 2023-02-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
