# Generated by Django 4.1.5 on 2023-02-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
